// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfxlprqblsrrihkiotcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1meGxwcnFibHNycmloa2lvdGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzY1ODcsImV4cCI6MjA1NTc1MjU4N30.MbS5fszanWYDu-Zrmxgq52-twoQdW4FQx9nBh9OTfdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);